SELECT max(length(LOGIN_NAME))+21,max(length(MOBILE))+21,max(length(ID_NUMBER))+21 FROM T_SES_BMS_USER
WHERE TYPE_ID IN(
SELECT "ID" FROM T_SES_SMS_SUPPLIER WHERE IS_DELETED = 0 AND IS_PROVISIONAL = 0 AND SUPPLIER_STATUS IN(-1,2)
AND CREATED_AT <= to_date('2018-09-14 23:50:00','yyyy-mm-dd hh24:mi:ss')-90
);

